name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  sonar:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      -
        name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      -
        name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      -
        name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      -
        name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
      -
        name: Cache deps
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      -
        name: Sonar
        if: ${{ env.SONAR_TOKEN != null }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            ./gradlew sonarqube \
              -Dsonar.pullrequest.provider=github \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=${SONAR_ORG_KEY} \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.projectVersion=${GITHUB_REF#refs/tags/} \
              -Dsonar.branch.name=master
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_BRANCH=${{ github.head_ref }}
            ./gradlew sonarqube \
              -Dsonar.pullrequest.provider=github \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.pullrequest.key=${{ github.event.number }} \
              -Dsonar.pullrequest.base=${{ github.base_ref }}
          else
            ./gradlew sonarqube \
              -Dsonar.pullrequest.provider=github \
              -Dsonar.pullrequest.github.repository=${{ github.repository }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.branch.name=${GITHUB_REF##*/}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
